name: End-to-end tests
on: push
jobs:
  install: 
   cypress-run:
    runs-on: ubuntu-22.04
     needs: install
    strategy:
      # don't fail the entire matrix on failure
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
         with:
          # Disable running of tests within install job
          runTests: false
          build: npm run build
        with:
          browser: chrome
        
        - name: Save build folder
        uses: actions/upload-artifact@v4
         with:
          name: build
        
         - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          group: 'UI-Chrome'
          start: npm start
        
      
        